### ISSUE TITLE
Options page showing "Selenium Java" in 3 places

### ISSUE THREAD

**Issue by TheDevilOfJesters** [mszeles/selenideium-element-inspector#22]
![image](https://user-images.githubusercontent.com/39665009/156895955-95a2abf5-dc0d-4f79-8bfb-21807a46e4bd.png)

I can see they're meant to be Selenium JS, Selenium C#, and the actual Selenium Java but kind of confusing to see 3 'Selenium Java'   Thankfully I use all 3 of those so I don't have to bother finding the right ones, but thought I'd mention it anyway. 

Installed this this morning hoping it'll save me a  lot of time in my projects thank you.

**Comment by mszeles** [comment]
Wow. Thanks for the report. I will fix it during the weekend. It will take some days till it will be available in the store. 
In case you can really save time please leave a review in Chrome Web Store. 😊
Thanks,
Miki

**Comment by JorchRL** [comment]
May I attempt to try to fix this bug? :D

**Comment by mszeles** [comment]
Thanks, @JorchRL and @TheDevilOfJesters for your contribution. I just merged the changes into the code, the new version will be available in a few days.
I've already bought a coffee for @JorchRL, but I would like to buy a coffee for you too @TheDevilOfJesters to show my gratitude. Just register on buymeacoffe.com and send me the link.
Cheers,
Miki
