### ISSUE TITLE
Links don't open

### ISSUE THREAD

**Issue by Omar8345** [mszeles/selenideium-element-inspector#32]
**Describe the bug**
When you click the extension it gets like a help window, it contains some links like **GitHub** and **Miki Szeles**. Those links when clicked don't open the link expected to open, it doesn't open any link at all. The attached screenshot has highlighted links and when they are clicked they don't open a website.

![image](https://user-images.githubusercontent.com/68811721/165302894-840d3a69-3e3f-4824-9867-295304ab973f.png)

**Input**
Steps to reproduce the behaviour:
1. Click on the extension
2. Click any of the links highlighted in the photo above
**(The link don't opens)**

**Acceptance Criteria (AC)**
That when a link is clicked like **GitHub**, it opens https://github.com/mszeles/selenideium-element-inspector/

**Desktop:**
 - OS: Windows 11
 - Browser: Microsoft Edge & Google Chrome

**Comment by mszeles** [comment]
Nice catch. 1 extra coffee is your reward. 😊
